[versions]
allure-java = "2.35.3"
allure-report = "3.4.1"
allure-gradle-plugin = "4.1.0"
assertj = "3.27.7"
awaitility = "4.3.0"
commons-codec = "1.22.0"
commons-compress = "1.28.0"
commons-lang3 = "3.20.0"
config = "1.4.9"
hikari = "7.1.0"
jackson = "2.22.1"
junit = "6.1.1"
kotlin = "2.4.0"
logback = "1.5.37"
postgresql = "42.7.13"
protobuf = "4.35.1"
rest-assured = "6.0.0"
slf4j = "2.0.18"
testcontainers = "2.0.5"

[plugins]
allure = { id = "io.qameta.allure", version.ref = "allure-gradle-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
allure-junit5 = { module = "io.qameta.allure:allure-junit5", version.ref = "allure-java" }
allure-rest-assured = { module = "io.qameta.allure:allure-rest-assured", version.ref = "allure-java" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
config = { module = "com.typesafe:config", version.ref = "config" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
